name: poor_web
description: light web wrapper library.
version: 2025.5.15
repository: https://github.com/a-skua/poor_web

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  web: ^1.1.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
